# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: 'en-US'
tone_instructions: 'You can use a friendly tone in your review.'
early_access: false
enable_free_tier: true
reviews:
  profile: 'assertive'
  request_changes_workflow: true
  high_level_summary: true
  poem: true
  review_status: true
  collapse_walkthrough: true
  auto_review:
    enabled: true
    auto_incremental_review: true
    drafts: false
chat:
  auto_reply: true
knowledge_base:
  learnings:
    scope: 'global'
  issues:
    scope: 'global'
  pull_requests:
    scope: 'global'
